title: "Rustacean Station"
encoding: UTF-8
author: "Rustacean Station"
email: podcast@rustacean-station.org
subtitle: "A community project for creating podcast content for the Rust programming language."
description: "Come journey with us into the weird, wonderful, and wily world of Rust."
lang: en-us
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true
repository: rustacean-station/rustacean-station.org
url: https://rustacean-station.org

exclude:
  - YYYY-MM-DD-template.md
  - vendor
  - audio
  - transcript_tools
  - transcript_style_guide.md
# can't use pages/_headers since Jekyll ignores _* files
# https://talk.jekyllrb.com/t/include-all-files-in-a-specific-directory-even-if-the-filenames-start-with-underscores/5849
include:
  - _headers
collections:
  episodes:
    output: true
    permalink: /episode/:title/
  transcripts:
    output: true
    permalink: /transcript/:title/

# https://github.com/jekyll/jekyll/issues/7744
defaults:
 - scope:
     path: ""
     type: "episodes"
   values:
     layout: "episode"
 - scope:
     path: ""
     type: "transcripts"
   values:
     layout: "transcript"
